# Generated by Django 4.1.7 on 2023-04-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('network_name', models.CharField(max_length=200)),
                ('ip', models.IntegerField()),
                ('hardware', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
        migrations.RenameModel(
            old_name='HostGroups',
            new_name='HostGroup',
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation_panel.hostgroup'),
        ),
    ]
