# Generated by Django 4.1.7 on 2023-05-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_panel', '0003_script_userlog_scriptresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptresult',
            name='run_for',
        ),
        migrations.AddField(
            model_name='scriptresult',
            name='run_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation_panel.host'),
        ),
    ]
