# Generated by Django 4.1.7 on 2023-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_panel', '0004_remove_scriptresult_run_for_scriptresult_run_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=15),
        ),
    ]
